spring.application.name=casamed-reminder

# Server port (different from Node.js)
server.port=8080

# CasaMed Node.js API base URL
casamed.api.url=http://localhost:5000

# WhatsApp Cloud API
whatsapp.token=EAASYrSuoAOwBRJYhcF9CfuB32elBQBlLYfHwKKI0giZALQ4rlicFZCMLZBHIUefs0rTCKrD4Ne6Hfdomhr7ZAD4ZCjur6ujFZBUISv5topm8giIfaqxJoZCpWjUQss3weqiBvu0cP6PZCuMAEXwsXoSEZA16sxtZAovNOYKWs6CQTGrxOQLVhZBNe8Fcfx8LxCGZBvb80kcGjuVPFytTLwZAZChtZBZB4r3NAklg4JrBLvkKTKsr8CDKXKwEVIlASDz2jHSbI6wcadaGNEOFmotOsXFNeZBX73DiQ
whatsapp.phone.id=1104571736063084

# Scheduler enabled
spring.task.scheduling.enabled=true
